version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbit
  redis:
    image: redis
    ports:
      - "6379:6379"
  rabbit:
    image: rabbitmq:3
